name: Build / Release
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build / Publish
        run: npm run dist
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/insight_browser-1.0.0.dmg
          asset_name: InsightBrowser.dmg
          asset_content_type: application/octet-stream