name: Build / Release
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build / Publish
        run: npm run dist
        env:
          GITHUB_TOKEN: ${{ secrets.insight }}
